### ISSUE TITLE
SQLInjection possible

### ISSUE THREAD

**Issue by darmiel** [SirSimon04/InfoPulli#1]
You should prepare the statement to avoid sql injections.
> see https://pynative.com/python-mysql-execute-parameterized-query-using-prepared-statement/

---

For example, I could enter `'; ANY QUERY; --`

Now the statement would be:

`SELECT avg_distance FROM scanned_locations JOIN persons WHERE scanned_locations.person_id = persons.id AND persons.short = '' ANY QUERY; --' ORDER BY scanned_locations.id DESC LIMIT 1;`

this is possible in these lines:

https://github.com/SirSimon04/InfoPulli/blob/master/server.py#L125
https://github.com/SirSimon04/InfoPulli/blob/master/server.py#L183
https://github.com/SirSimon04/InfoPulli/blob/master/server.py#L225

**Comment by CodingAna** [comment]
Thanks, I hopefully removed all possible vulnerabilities :D

**Comment by darmiel** [comment]
https://github.com/SirSimon04/InfoPulli/blob/82ac28855a4ed3f9a6e46c89db25c506d54606b7/server.py#L220-L223

Since you're now using a parameterized query, you don't need to escape the values using `''`.
By surrounding the input value with `'` the input is escaped again to `'\'test\''`. 
Also, note that `NULL` is inserted as a string, not as an actual null value.

cc/ @LukasBaginski
