### ISSUE TITLE
Use `send_from_directory` instead of `send_file`

### ISSUE THREAD

**Issue by darmiel** [SirSimon04/InfoPulli#3]
https://github.com/SirSimon04/InfoPulli/blob/82ac28855a4ed3f9a6e46c89db25c506d54606b7/server.py#L259-L260

You should use [send_from_directory](https://flask.palletsprojects.com/en/1.1.x/api/#flask.send_from_directory) because [send_file](https://flask.palletsprojects.com/en/1.1.x/api/#flask.send_file) accepts, for example, `../../../../etc/passwd`

From the official documentation:

> Please never pass filenames to this function from user sources; you should use [send_from_directory()](https://flask.palletsprojects.com/en/1.1.x/api/#flask.send_from_directory) instead.

Since only files in the root directory are allowed anyway (e.g. /index.html, /test.js) - according to the route

https://github.com/SirSimon04/InfoPulli/blob/82ac28855a4ed3f9a6e46c89db25c506d54606b7/server.py#L237

and no files from subdirectories (/a/b.html), it makes no difference anyway and is simply more secure.

**Comment by CodingAna** [comment]
I've added a `safe_join` to handle the input, files should be safe now.
The variable `directories` can contain subdirectories (i.e. `/assets/FontManifest.json`) and `safe_join` seems like a better solution for such cases.
Thanks!
